version: 2.1
 
jobs:
  build:
    parallelism: 1
    docker:
      - image: alpine
    steps:
      - checkout
      - run: sleep 200s

workflows:
  test:
    jobs:
      - build:
         name: "build1"
      - build:
         name: "build2"
      - build:
         name: "build3"
      - build:
         name: "build4"
